version: "3.9"

services:
  loki:
    image: grafana/loki:3.5.4
    container_name: loki
    restart: unless-stopped

    command:
      - "-config.file=/etc/loki/config.yml"

    ports:
      - "3100:3100"

    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - ./data/loki:/loki

    networks:
      - loki-network

networks:
  loki-network:
    driver: bridge
