<?php
// Serves the Grafana Alloy config for a monitored server's log sources.
// Authenticated the same way as agent.php (a per-server key), but read via GET
// since this is a config file fetch, not a data push. ETag/If-None-Match let the
// agent-side wrapper skip a reload when nothing changed.
//
// Config content itself never touches log lines - it only tells Alloy WHERE to
// tail and HOW to filter/label/rate-limit at the edge, per app_servers_logsources.

$debug = false;
if ($debug) {
    error_reporting(E_ALL & ~E_NOTICE);
    ini_set('display_errors', '1');
} else {
    // error_reporting(0) doesn't just hide errors from the response, it also stops
    // PHP from logging them anywhere (log_errors respects the reporting level) -
    // see docs/incidents/2026-09-14.md. Keep display off but keep logging on.
    error_reporting(E_ALL);
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
}

$scriptpath = __DIR__;

require($scriptpath . '/includes/functions.php');
spl_autoload_register('vendorClassAutoload');
spl_autoload_register('appClassAutoload');
require($scriptpath . '/config.php');

$database = new medoo($config);

date_default_timezone_set(getConfigValue("timezone"));

$serverkey = $_GET['serverkey'] ?? '';
if ($serverkey === '') { http_response_code(400); die("No server key received."); }

$server = $database->get("app_servers", "*", [ "serverkey" => $serverkey ]);
if (empty($server)) { http_response_code(404); die("Unknown server."); }

// Backfill: servers created before this feature shipped have no logs_token yet.
// Server::add() generates one for new servers; this covers everyone else.
if (empty($server['logs_token'])) {
    $server['logs_token'] = randomString(64);
    $database->update("app_servers", [ "logs_token" => $server['logs_token'] ], [ "id" => $server['id'] ]);
}

$sources = $database->select("app_servers_logsources", "*", [ "AND" => [ "serverid" => $server['id'], "status" => 1 ] ]);

$pushUrl = getConfigValue('loki_push_url');
if ($pushUrl === '') {
    // Default: same host as the app, on the Loki-proxy's published port.
    // Operators who want single-port ingress can reverse-proxy this path through
    // their existing HTTPS vhost and set loki_push_url explicitly instead.
    $host = parse_url(baseURL(), PHP_URL_HOST) ?: $_SERVER['SERVER_NAME'];
    $scheme = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? 'https' : 'http';
    $pushUrl = $scheme . '://' . $host . ':3100';
}

$riverConfig = buildAlloyConfig($sources, $pushUrl, $server['logs_token']);

$etag = '"' . hash('sha256', $riverConfig) . '"';

$ifNoneMatch = $_SERVER['HTTP_IF_NONE_MATCH'] ?? '';
if ($ifNoneMatch !== '' && trim($ifNoneMatch) === $etag) {
    http_response_code(304);
    header('ETag: ' . $etag);
    exit;
}

header('Content-Type: text/plain; charset=utf-8');
header('ETag: ' . $etag);
echo $riverConfig;


// ----------------------------------------------------------------------------------------------
// ALLOY CONFIG GENERATION
// ----------------------------------------------------------------------------------------------

function riverString($value) {
    // River double-quoted strings escape like Go strings: backslash, then quote.
    // Values here are single-line (paths, regexes, tokens) - strip any newline
    // that would otherwise break out of the string literal.
    $value = str_replace(["\r", "\n"], '', (string)$value);
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
}

function riverLabelKey($key) {
    // River map keys in this context are bare identifiers - only allow the
    // characters that are actually valid there, everything else is dropped
    // rather than risk generating unparseable config from admin-entered labels.
    return preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $key) ? $key : null;
}

function buildAlloyConfig(array $sources, $pushUrl, $logsToken) {
    $out = "// Generated by agentconfig.php - do not edit by hand, changes will be overwritten.\n\n";

    $receivers = [];

    foreach ($sources as $source) {
        if ($source['mode'] === 'disabled') continue;

        $id = 'source_' . (int)$source['id'];
        $out .= buildSourceBlock($id, $source);
        $receivers[] = "loki.process.{$id}.receiver";
    }

    $out .= "loki.write \"default\" {\n";
    $out .= "  endpoint {\n";
    $out .= "    url = \"" . riverString(rtrim($pushUrl, '/') . '/loki/api/v1/push') . "\"\n";
    $out .= "    headers = {\n";
    $out .= "      \"X-Logs-Token\" = \"" . riverString($logsToken) . "\",\n";
    $out .= "    }\n";
    $out .= "  }\n";
    $out .= "}\n";

    return $out;
}

function buildSourceBlock($id, array $source) {
    $out = "";

    $out .= "local.file_match \"{$id}\" {\n";
    $out .= "  path_targets = [{\"__path__\" = \"" . riverString($source['path_glob']) . "\"}]\n";
    $out .= "}\n\n";

    $out .= "loki.source.file \"{$id}\" {\n";
    $out .= "  targets    = local.file_match.{$id}.targets\n";
    $out .= "  forward_to = [loki.process.{$id}.receiver]\n";
    $out .= "}\n\n";

    $out .= "loki.process \"{$id}\" {\n";

    if (!empty($source['multiline_pattern'])) {
        $out .= "  stage.multiline {\n";
        $out .= "    firstline     = \"" . riverString($source['multiline_pattern']) . "\"\n";
        $out .= "    max_wait_time = \"3s\"\n";
        $out .= "  }\n\n";
    }

    // ---- level classification: every mode gets this, "errors_only" also filters on it ----
    $out .= "  stage.regex {\n";
    $out .= "    expression = \"(?i)(?P<crit_hit>CRITICAL|FATAL|PANIC|EMERG|ALERT)\"\n";
    $out .= "  }\n";
    $out .= "  stage.regex {\n";
    $out .= "    expression = \"(?i)(?P<warn_hit>WARN(?:ING)?)\"\n";
    $out .= "  }\n";
    $out .= "  stage.regex {\n";
    $out .= "    expression = \"(?i)(?P<err_hit>ERROR|Exception|Traceback)\"\n";
    $out .= "  }\n";
    $out .= "  stage.template {\n";
    $out .= "    source   = \"level\"\n";
    $out .= "    template = \"{{ if .crit_hit }}crit{{ else if .warn_hit }}warn{{ else if .err_hit }}error{{ else }}info{{ end }}\"\n";
    $out .= "  }\n";

    if ($source['mode'] === 'errors_only') {
        $out .= "  stage.drop {\n";
        $out .= "    source     = \"level\"\n";
        $out .= "    expression = \"^info$\"\n";
        $out .= "  }\n";
    }

    if ($source['mode'] === 'filtered') {
        if (!empty($source['exclude_regex'])) {
            $out .= "  stage.drop {\n";
            $out .= "    expression = \"" . riverString($source['exclude_regex']) . "\"\n";
            $out .= "  }\n";
        }
        if (!empty($source['include_regex'])) {
            $out .= "  stage.regex {\n";
            $out .= "    expression = \"(?P<include_hit>" . riverString($source['include_regex']) . ")\"\n";
            $out .= "  }\n";
            $out .= "  stage.drop {\n";
            $out .= "    source     = \"include_hit\"\n";
            $out .= "    expression = \"^$\"\n";
            $out .= "  }\n";
        }
    }

    $out .= "  stage.labels {\n";
    $out .= "    values = {\n";
    $out .= "      level = \"\",\n";
    $out .= "    }\n";
    $out .= "  }\n";

    $staticLabels = [ 'serverid' => (string)$source['serverid'], 'sourceid' => (string)$source['id'] ];
    $extra = @unserialize($source['labels']);
    if (is_array($extra)) {
        foreach ($extra as $k => $v) {
            $key = riverLabelKey($k);
            if ($key !== null) $staticLabels[$key] = (string)$v;
        }
    }
    $out .= "  stage.static_labels {\n";
    $out .= "    values = {\n";
    foreach ($staticLabels as $k => $v) {
        $out .= "      {$k} = \"" . riverString($v) . "\",\n";
    }
    $out .= "    }\n";
    $out .= "  }\n";

    // Rate limiting is real Alloy stage.limit - it drops over-rate lines without a
    // marker line in the stream (Alloy has no such primitive). The visible-gap
    // requirement is met instead via app_servers_logs_agentstate's lines_dropped
    // counter, not a synthetic log line.
    $rateLimit = (int)($source['rate_limit'] ?? 0);
    if ($rateLimit > 0) {
        $out .= "  stage.limit {\n";
        $out .= "    rate  = {$rateLimit}\n";
        $out .= "    burst = {$rateLimit}\n";
        $out .= "    by_label_name = \"\"\n";
        $out .= "    drop      = true\n";
        $out .= "  }\n";
    }

    $sampleRate = (int)($source['sample_rate'] ?? 1);
    if ($sampleRate > 1) {
        $rate = round(1 / $sampleRate, 6);
        $out .= "  stage.sampling {\n";
        $out .= "    rate = {$rate}\n";
        $out .= "  }\n";
    }

    $out .= "  forward_to = [loki.write.default.receiver]\n";
    $out .= "}\n\n";

    return $out;
}
